### ISSUE TITLE
Points can not be filtered using state, city or municipality 

### ISSUE THREAD

**Issue by nishontan** [naxadeve/iom-open-space-portal#41]

**Comment by igaurab** [comment]
The administrative division of Nepal consists of `Provinces`, `Districts` and `Municipalities` resp. Also if we look into these models we find the reference of `province` in `district` and `district` in `municipalities`, which represents their hierarchy.

So to filter the points first we should filter the list of 

1. `Districts` and `Municipalities` if Province is changed.
2. `Municipalities` if `Districts` is changed.
3. Automatically populate the `District` and `Province` when a municipality is selected
4. Automatically populate `Province` and filter the list of `Municipality` if `District` is selected
and so on....

For this we can listen to the stream of `Province`, `District` and `Municipality` and perform the required filtering inside  it.

**Comment by nishontan** [comment]
@igaurab 
Is this a know issue ?
![ezgif-6-c33d3bedbe1a](https://user-images.githubusercontent.com/11831955/70592166-f0938980-1c00-11ea-8f1e-b8869c3e6224.gif)
